apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: your-service-name  # Replace with your service name
  namespace: 'default'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'  # Set maximum instances to 5
    spec:
      containers:
      - image: gcr.io/your-project-id/your-image-name  # Replace with your container image
        resources:
          limits:
            memory: '256Mi'  # Adjust memory limit as needed
            cpu: '500m'  # Adjust CPU limit as needed
